//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoescola
{
    using System;
    using System.Collections.Generic;
    
    public partial class rematricula
    {
        public int id { get; set; }
        public int idaluno { get; set; }
        public string sobrenome { get; set; }
        public string cpf { get; set; }
        public System.DateTime datanascimento { get; set; }
        public string rematricula1 { get; set; }
        public string semestre { get; set; }
        public string unidade { get; set; }
    
        public virtual alunos alunos { get; set; }
    }
}
